#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Box2D-Packed contributors
# SPDX-License-Identifier: MIT
"""
box2d_unity: Box2D-Packed as the 2D physics backend for crust's tools/unity_pack.py.

unity_pack packs a Unity-shaped project into engine.c / data.c. Its data tables describe every
Rigidbody2D (_Rigidbody2D_*) and Collider2D (_Collider2D_*), and its engine sends
OnCollisionEnter2D / Stay2D / Exit2D by comparing each fixed step's touching pairs with the
previous step's. With `unity_pack.py --physics box2d`, this module replaces unity_pack's own
integrator and AABB contacts with a Box2D world, and keeps everything else:

    engine_physics_fixed()                 (engine.c, unity_pack)
        engine_box2d_step()                (physics_box2d.c, generated here)
            push script changes: velocity, teleports, gravity scale, damping, world gravity
            b2World_Step
            pull positions and velocities into the packed tables
            report touching pairs with engine_col2d_contact()
        engine_physics_collide2d_messages() (unity_pack: Enter / Stay / Exit, after the step)

Touching pairs come from Box2D contact begin and end events. With `--physics-inject`, they come
from box2d_pack injection markers instead: the injected code only records the pair, so scripts
still run after the step, as in Unity.

engine.c exports what the glue needs, in unity_pack's C subset:

    void engine_rb2d_get_pos( int rb, float* x, float* y );   Rigidbody2D owner position
    void engine_rb2d_set_pos( int rb, float x, float y );
    void engine_col2d_center( int ci, float* x, float* y );  collider world center
    void engine_col2d_contact( int a, int b );               report a touching pair

Mapping:
    Rigidbody2D Dynamic / Kinematic / Static  ->  b2_dynamicBody / kinematic / static, rotation
                                                  locked (unity_pack has no rigidbody rotation)
    BoxCollider2D / CircleCollider2D          ->  offset box / circle, rotated by the collider
    Collider2D without a Rigidbody2D          ->  static body at the collider center
    m_IsTrigger                               ->  sensor, no collision messages
    Rigidbody2D mass                          ->  body mass
    friction / bounciness + combine modes     ->  world friction / restitution callbacks that
                                                  apply Unity's PhysicsMaterialCombine rules
"""

import json
import os
import sys

__all__ = ["emit_glue", "build_library", "GLUE_FILE", "INJECT_FILE"]

GLUE_FILE = "physics_box2d.c"
INJECT_FILE = "box2d_inject.json"

_HERE = os.path.dirname( os.path.abspath( __file__ ) )


def _counts( plan ):
    rb = len( plan.get( "rigidbody2d" ) or [] )
    col = len( plan.get( "collider2d" ) or [] )
    return rb, col


def emit_glue( outdir, plan, inject=False, sub_steps=4 ):
    """Write physics_box2d.c (and box2d_inject.json when inject) into outdir. Returns the paths."""
    rb_count, col_count = _counts( plan )
    n_rb = max( 1, rb_count )
    n_col = max( 1, col_count )
    max_pairs = max( 1, col_count * ( col_count - 1 ) // 2 )

    glue = GLUE_TEMPLATE.format(
        N_RB=n_rb,
        N_COL=n_col,
        MAX_PAIRS=max_pairs,
        SUB_STEPS=int( sub_steps ),
    )
    paths = []
    glue_path = os.path.join( outdir, GLUE_FILE )
    _write_if_different( glue_path, glue )
    paths.append( glue_path )

    inject_path = os.path.join( outdir, INJECT_FILE )
    if inject:
        spec = {
            "comment": "Generated by box2d_unity.py for unity_pack --physics box2d --physics-inject. "
                       "Record touching pairs at the contact markers; scripts run after the step.",
            "defines": {
                "B2_PACK_NO_CONTACT_BEGIN_ARRAY": 1,
                "B2_PACK_NO_CONTACT_END_ARRAY": 1,
            },
            "globals": [
                "void b2u_on_begin( int colliderA, int colliderB );",
                "void b2u_on_end( int colliderA, int colliderB );",
            ],
            "inject": [
                {
                    "event": "contact_begin",
                    "code": "b2u_on_begin( (int)(intptr_t)shapeA->userData - 1, (int)(intptr_t)shapeB->userData - 1 );",
                },
                {
                    "event": "contact_end",
                    "code": "b2u_on_end( (int)(intptr_t)shapeA->userData - 1, (int)(intptr_t)shapeB->userData - 1 );",
                },
            ],
        }
        _write_if_different( inject_path, json.dumps( spec, indent=2 ) + "\n" )
        paths.append( inject_path )
    elif os.path.exists( inject_path ):
        os.remove( inject_path )
    return paths


def build_library( outdir, inject=False, lto=False, box2d_root=None, verbose=False ):
    """
    Build Box2D-Packed for this pack with box2d_pack, into outdir/box2d.
    Returns (library path, include directory, extra compiler defines for the glue).
    """
    root = os.path.abspath( box2d_root or _HERE )
    if root not in sys.path:
        sys.path.insert( 0, root )
    import box2d_pack  # noqa: E402

    inject_path = os.path.join( outdir, INJECT_FILE ) if inject else None
    result = box2d_pack.build(
        None,
        inject_path,
        build_dir=os.path.join( outdir, "box2d" ),
        lto=lto,
        repo_root=root,
        verbose=verbose,
    )
    include_dir = os.path.join( result.source_dir, "include" )
    defines = ["-DB2_PACK_INJECTED=1"] if inject else []
    return result.lib, include_dir, defines


def _write_if_different( path, text ):
    try:
        with open( path, encoding="utf-8" ) as f:
            if f.read() == text:
                return
    except OSError:
        pass
    with open( path, "w", encoding="utf-8" ) as f:
        f.write( text )


GLUE_TEMPLATE = r"""/* Generated by box2d_unity.py for unity_pack --physics box2d. Do not edit. */

#include "box2d/box2d.h"

#include <stdint.h>

#ifndef B2_PACK_INJECTED
#define B2_PACK_INJECTED 0
#endif

/* unity_pack tables (data.c) */
extern float Time_fixedDeltaTime;
extern float Physics2D_gravity_x;
extern float Physics2D_gravity_y;
extern int _Rigidbody2D_count;
extern float _Rigidbody2D_vel_x[];
extern float _Rigidbody2D_vel_y[];
extern float _Rigidbody2D_gravity_scale[];
extern float _Rigidbody2D_linear_damping[];
extern float _Rigidbody2D_mass[];
extern int _Rigidbody2D_body_type[];
extern const int _Collider2D_count;
extern const int _Collider2D_kind[];
extern const int _Collider2D_is_trigger[];
extern const int _Collider2D_rb2d[];
extern const float _Collider2D_ox[];
extern const float _Collider2D_oy[];
extern const float _Collider2D_hw[];
extern const float _Collider2D_hh[];
extern const float _Collider2D_cos[];
extern const float _Collider2D_sin[];
extern const float _Collider2D_friction[];
extern const float _Collider2D_bounciness[];
extern const int _Collider2D_friction_combine[];
extern const int _Collider2D_bounce_combine[];

/* unity_pack exports (engine.c, --physics box2d) */
void engine_rb2d_get_pos( int rb, float* x, float* y );
void engine_rb2d_set_pos( int rb, float x, float y );
void engine_col2d_center( int ci, float* x, float* y );
void engine_col2d_contact( int a, int b );

void engine_box2d_step( void );
void b2u_on_begin( int colliderA, int colliderB );
void b2u_on_end( int colliderA, int colliderB );

enum
{{
	B2U_MAX_RB = {N_RB},
	B2U_MAX_COL = {N_COL},
	B2U_MAX_PAIRS = {MAX_PAIRS},
	B2U_SUB_STEPS = {SUB_STEPS},
}};

static int b2u_ready;
static b2WorldId b2u_world;
static b2BodyId b2u_rb_body[B2U_MAX_RB];
static float b2u_last_x[B2U_MAX_RB];
static float b2u_last_y[B2U_MAX_RB];

/* Touching collider pairs, lo < hi, maintained from contact begin and end */
static int b2u_pair_a[B2U_MAX_PAIRS];
static int b2u_pair_b[B2U_MAX_PAIRS];
static int b2u_pair_n;

void b2u_on_begin( int colliderA, int colliderB )
{{
	int lo = colliderA < colliderB ? colliderA : colliderB;
	int hi = colliderA < colliderB ? colliderB : colliderA;
	if ( lo < 0 || lo == hi )
	{{
		return;
	}}
	for ( int i = 0; i < b2u_pair_n; ++i )
	{{
		if ( b2u_pair_a[i] == lo && b2u_pair_b[i] == hi )
		{{
			return;
		}}
	}}
	if ( b2u_pair_n < B2U_MAX_PAIRS )
	{{
		b2u_pair_a[b2u_pair_n] = lo;
		b2u_pair_b[b2u_pair_n] = hi;
		b2u_pair_n += 1;
	}}
}}

void b2u_on_end( int colliderA, int colliderB )
{{
	int lo = colliderA < colliderB ? colliderA : colliderB;
	int hi = colliderA < colliderB ? colliderB : colliderA;
	for ( int i = 0; i < b2u_pair_n; ++i )
	{{
		if ( b2u_pair_a[i] == lo && b2u_pair_b[i] == hi )
		{{
			/* Keep order stable, messages are sent in pair order */
			for ( int k = i + 1; k < b2u_pair_n; ++k )
			{{
				b2u_pair_a[k - 1] = b2u_pair_a[k];
				b2u_pair_b[k - 1] = b2u_pair_b[k];
			}}
			b2u_pair_n -= 1;
			return;
		}}
	}}
}}

/* PhysicsMaterialCombine: Average=0 Multiply=1 Minimum=2 Maximum=3, the higher mode wins */
static float b2u_combine( float a, float b, int ca, int cb )
{{
	int mode = ca > cb ? ca : cb;
	if ( mode > 3 )
		mode = 0;
	if ( mode == 1 )
		return a * b;
	if ( mode == 2 )
		return a < b ? a : b;
	if ( mode == 3 )
		return a > b ? a : b;
	return 0.5f * ( a + b );
}}

/* userMaterialId carries the combine modes: friction in bits 0-7, bounce in bits 8-15 */
static float b2u_friction( float a, uint64_t ma, float b, uint64_t mb )
{{
	return b2u_combine( a, b, (int)( ma & 0xff ), (int)( mb & 0xff ) );
}}

static float b2u_restitution( float a, uint64_t ma, float b, uint64_t mb )
{{
	return b2u_combine( a, b, (int)( ( ma >> 8 ) & 0xff ), (int)( ( mb >> 8 ) & 0xff ) );
}}

static b2BodyType b2u_body_type( int unityType )
{{
	/* Rigidbody2D.bodyType: Dynamic=0 Kinematic=1 Static=2 */
	if ( unityType == 1 )
		return b2_kinematicBody;
	if ( unityType == 2 )
		return b2_staticBody;
	return b2_dynamicBody;
}}

static void b2u_add_shape( b2BodyId bodyId, int ci, b2Vec2 offset )
{{
	b2ShapeDef def = b2DefaultShapeDef();
	def.userData = (void*)(intptr_t)( ci + 1 );
	def.material.friction = _Collider2D_friction[ci];
	def.material.restitution = _Collider2D_bounciness[ci];
	def.material.userMaterialId =
		(uint64_t)( _Collider2D_friction_combine[ci] & 0xff ) | ( (uint64_t)( _Collider2D_bounce_combine[ci] & 0xff ) << 8 );
	def.isSensor = _Collider2D_is_trigger[ci] != 0;
	def.enableContactEvents = _Collider2D_is_trigger[ci] == 0;

	b2Rot rotation = {{ _Collider2D_cos[ci], _Collider2D_sin[ci] }};
	if ( _Collider2D_kind[ci] == 1 )
	{{
		b2Circle circle = {{ offset, _Collider2D_hw[ci] }};
		b2CreateCircleShape( bodyId, &def, &circle );
	}}
	else
	{{
		b2Polygon box = b2MakeOffsetBox( _Collider2D_hw[ci], _Collider2D_hh[ci], offset, rotation );
		b2CreatePolygonShape( bodyId, &def, &box );
	}}
}}

static void b2u_create( void )
{{
	b2WorldDef worldDef = b2DefaultWorldDef();
	worldDef.gravity = (b2Vec2){{ Physics2D_gravity_x, Physics2D_gravity_y }};
	worldDef.frictionCallback = b2u_friction;
	worldDef.restitutionCallback = b2u_restitution;
	b2u_world = b2CreateWorld( &worldDef );

	for ( int rb = 0; rb < _Rigidbody2D_count && rb < B2U_MAX_RB; ++rb )
	{{
		float x, y;
		engine_rb2d_get_pos( rb, &x, &y );
		b2BodyDef def = b2DefaultBodyDef();
		def.type = b2u_body_type( _Rigidbody2D_body_type[rb] );
		def.position = (b2Pos){{ x, y }};
		def.linearVelocity = (b2Vec2){{ _Rigidbody2D_vel_x[rb], _Rigidbody2D_vel_y[rb] }};
		def.gravityScale = _Rigidbody2D_gravity_scale[rb];
		def.linearDamping = _Rigidbody2D_linear_damping[rb];
		def.motionLocks.angularZ = true;
		b2u_rb_body[rb] = b2CreateBody( b2u_world, &def );
		b2u_last_x[rb] = x;
		b2u_last_y[rb] = y;
	}}

	for ( int ci = 0; ci < _Collider2D_count && ci < B2U_MAX_COL; ++ci )
	{{
		int rb = _Collider2D_rb2d[ci];
		if ( rb >= 0 && rb < _Rigidbody2D_count )
		{{
			/* Offset relative to the body origin, rotated like the collider */
			float c = _Collider2D_cos[ci], s = _Collider2D_sin[ci];
			float ox = _Collider2D_ox[ci], oy = _Collider2D_oy[ci];
			b2u_add_shape( b2u_rb_body[rb], ci, (b2Vec2){{ c * ox - s * oy, s * ox + c * oy }} );
		}}
		else
		{{
			float x, y;
			engine_col2d_center( ci, &x, &y );
			b2BodyDef def = b2DefaultBodyDef();
			def.position = (b2Pos){{ x, y }};
			b2BodyId bodyId = b2CreateBody( b2u_world, &def );
			b2u_add_shape( bodyId, ci, b2Vec2_zero );
		}}
	}}

	/* Rigidbody2D.mass: scale the shape-derived mass data to the authored mass */
	for ( int rb = 0; rb < _Rigidbody2D_count && rb < B2U_MAX_RB; ++rb )
	{{
		if ( _Rigidbody2D_body_type[rb] != 0 || _Rigidbody2D_mass[rb] <= 0.0f )
			continue;
		b2MassData md = b2Body_GetMassData( b2u_rb_body[rb] );
		float mass = _Rigidbody2D_mass[rb];
		if ( md.mass > 0.0f )
		{{
			md.rotationalInertia *= mass / md.mass;
		}}
		md.mass = mass;
		b2Body_SetMassData( b2u_rb_body[rb], md );
	}}

	b2u_pair_n = 0;
	b2u_ready = 1;
}}

void engine_box2d_step( void )
{{
	if ( b2u_ready == 0 )
	{{
		b2u_create();
	}}

	/* Push what scripts may have changed since the last step */
	b2World_SetGravity( b2u_world, (b2Vec2){{ Physics2D_gravity_x, Physics2D_gravity_y }} );
	for ( int rb = 0; rb < _Rigidbody2D_count && rb < B2U_MAX_RB; ++rb )
	{{
		b2BodyId bodyId = b2u_rb_body[rb];
		float x, y;
		engine_rb2d_get_pos( rb, &x, &y );
		if ( x != b2u_last_x[rb] || y != b2u_last_y[rb] )
		{{
			/* transform.position written by a script */
			b2Body_SetTransform( bodyId, (b2Pos){{ x, y }}, b2Rot_identity );
		}}
		if ( _Rigidbody2D_body_type[rb] != 2 )
		{{
			b2Body_SetLinearVelocity( bodyId, (b2Vec2){{ _Rigidbody2D_vel_x[rb], _Rigidbody2D_vel_y[rb] }} );
		}}
		if ( _Rigidbody2D_body_type[rb] == 0 )
		{{
			b2Body_SetGravityScale( bodyId, _Rigidbody2D_gravity_scale[rb] );
			b2Body_SetLinearDamping( bodyId, _Rigidbody2D_linear_damping[rb] );
		}}
	}}

	float dt = Time_fixedDeltaTime > 1e-8f ? Time_fixedDeltaTime : 0.02f;
	b2World_Step( b2u_world, dt, B2U_SUB_STEPS );

#if B2_PACK_INJECTED == 0
	/* Standard API: touching pairs from the contact event arrays */
	b2ContactEvents events = b2World_GetContactEvents( b2u_world );
	for ( int i = 0; i < events.beginCount; ++i )
	{{
		b2ContactBeginTouchEvent* e = events.beginEvents + i;
		b2u_on_begin( (int)(intptr_t)b2Shape_GetUserData( e->shapeIdA ) - 1,
					  (int)(intptr_t)b2Shape_GetUserData( e->shapeIdB ) - 1 );
	}}
	for ( int i = 0; i < events.endCount; ++i )
	{{
		b2ContactEndTouchEvent* e = events.endEvents + i;
		if ( b2Shape_IsValid( e->shapeIdA ) && b2Shape_IsValid( e->shapeIdB ) )
		{{
			b2u_on_end( (int)(intptr_t)b2Shape_GetUserData( e->shapeIdA ) - 1,
						(int)(intptr_t)b2Shape_GetUserData( e->shapeIdB ) - 1 );
		}}
	}}
#endif

	/* Pull positions and velocities into the packed tables */
	for ( int rb = 0; rb < _Rigidbody2D_count && rb < B2U_MAX_RB; ++rb )
	{{
		b2BodyId bodyId = b2u_rb_body[rb];
		b2Pos p = b2Body_GetPosition( bodyId );
		b2Vec2 v = b2Body_GetLinearVelocity( bodyId );
		float x = (float)p.x, y = (float)p.y;
		engine_rb2d_set_pos( rb, x, y );
		b2u_last_x[rb] = x;
		b2u_last_y[rb] = y;
		_Rigidbody2D_vel_x[rb] = v.x;
		_Rigidbody2D_vel_y[rb] = v.y;
	}}

	/* unity_pack sends Enter / Stay / Exit by comparing with the previous step */
	for ( int i = 0; i < b2u_pair_n; ++i )
	{{
		engine_col2d_contact( b2u_pair_a[i], b2u_pair_b[i] );
	}}
}}
"""
