#!/usr/bin/env python3
"""
Generate cachegrind_table.tex from Cachegrind logs.

Usage: python3 make_cachegrind_table.py LOG_DIR > cachegrind_table.tex

LOG_DIR holds u.<scene>.log (Box2D v3) and head.<scene>.log (Box2D-Packed), each the stderr of

  valgrind --tool=cachegrind --cache-sim=yes --I1=32768,8,64 --D1=32768,8,64 \\
           --LL=8388608,16,64 benchmark -t=1 -w=1 -r=1 -b=<scene>
"""
import os
import re
import sys

SCENES = ["tile_world", "queries", "tree_cast", "smash", "large_pyramid", "many_pyramids", "joint_grid"]


def counts( path ):
    text = open( path ).read()
    get = lambda key: int( re.search( key + r":\s+([\d,]+)", text ).group( 1 ).replace( ",", "" ) )
    return get( r"I refs" ), get( r"D1  misses" ), get( r"LLd misses" )


def pct( new, old ):
    value = ( new - old ) / old * 100.0
    text = f"{value:+.1f}\\%".replace( "-", "$-$" )
    return f"\\textbf{{{text}}}" if value <= -5.0 else text


def main():
    log_dir = sys.argv[1]
    rows = []
    for scene in SCENES:
        old = os.path.join( log_dir, f"u.{scene}.log" )
        new = os.path.join( log_dir, f"head.{scene}.log" )
        if not ( os.path.exists( old ) and os.path.exists( new ) ):
            continue
        ( i0, d0, l0 ), ( i1, d1, l1 ) = counts( old ), counts( new )
        name = scene.replace( "_", "\\_" )
        rows.append( f"\\texttt{{{name}}} & {pct( i1, i0 )} & {pct( d1, d0 )} & {pct( l1, l0 )} \\\\" )

    print( "% Generated by make_cachegrind_table.py, do not edit" )
    print( "\\begin{table}[t]" )
    print( "\\centering\\small" )
    print( "\\caption{Box2D-Packed relative to Box2D v3 under Cachegrind (32\\,KB L1, 8\\,MB LL, one worker)." )
    print( "Changes of 5\\% or more are in bold. Negative is better.}" )
    print( "\\label{tab:cumulative}" )
    print( "\\begin{tabular}{lrrr}" )
    print( "\\toprule" )
    print( "Scene & Instr. & L1 data & LL data \\\\" )
    print( "\\midrule" )
    for row in rows:
        print( row )
    print( "\\bottomrule" )
    print( "\\end{tabular}" )
    print( "\\end{table}" )


if __name__ == "__main__":
    main()
